############################## default configuration ##############################
title = "BKISC - CLB ATTT HCMUT"
timeZone = "Asia/Ho_Chi_Minh"
theme = "andromeda-light"
removePathAccents = true
# post pagination
paginate = "8"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "themefisher-template" # get your shortname form here : https://disqus.com

############################## Outputs ##############################
[outputs]
home = ["HTML", "RSS", "WebAppManifest"]

[imaging]
quality = 100

[mediaTypes]

[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]

[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

############################## Cache ##############################
[caches]

[caches.assets]
dir = ":cacheDir/_gen"
maxAge = "720h"

[caches.getcsv]
dir = ":cacheDir/:project"
maxAge = "720h"

[caches.getjson]
dir = ":cacheDir/:project"
maxAge = "720h"

[caches.getresource]
dir = ":cacheDir/:project"
maxAge = "720h"

[caches.images]
dir = ":cacheDir/_gen"
maxAge = "720h"

[caches.modules]
dir = ":cacheDir/modules"
maxAge = "720h"

############################## Markup language ##############################
[markup]

[markup.goldmark.renderer]
unsafe = true
