# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "/about/"
weight = 2

[[main]]
name = "Blog"
url = "https://blog.bkisc.com/"
weight = 3

[[main]]
name = "Members"
url = "https://blog.bkisc.com/members/"
weight = 4

[[main]]
name = "Contact"
url = "/contact/"
weight = 5

# footer menu
[[footer]]
name = "Privacy & Policy"
url = "/privacy-and-policy/"
weight = 1

[[footer]]
name = "Terms & Conditions"
url = "/terms-and-conditions/"
weight = 2
