version: "3.8"

services:
    build:
        image: klakegg/hugo:ext-alpine
        volumes:
            - .:/src

    server:
        extends:
            service: build
        command: server
        ports:
            - 1313:1313
