baseURL = "https://bkisc.com" # This line will be set to: baseURL = "https://bkisc.com" after doublevkay reset
# google analytics
googleAnalytics = "" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
